name: Deploy

on:
  schedule:
    # UTC时间，比中国时间慢8h, 昨天22:30 -> 今天6:30
    # 翻译：每周一、五、六的22:30触发，即中国时间，每周三、六、七的6:30触发
    - cron: '15 22 * * *'
#    - cron: '30 22 * * 4,5'

  workflow_dispatch:

jobs:
  reverse:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install packages 
        run: pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

      - name: Run the script
        env:
          XUHAO: ${{ secrets.XUHAO }}
          MIMA: ${{ secrets.MIMA }}
          XUHAO1: ${{ secrets.XUHAO1 }}
          MIMA1: ${{ secrets.MIMA1 }}
        run: python reserve.py
